### ISSUE TITLE
com.google.gson.JsonSyntaxException: java.lang.IllegalStateException: Expected a string but was BEGIN_OBJECT at line 1 column 724 path $[0].caption

### ISSUE THREAD

**Issue by gregoryenriquez** [huishen12/Inscat#1]
10-15 16:34:17.475 29511-29720/com.spacebunny.hshen.inscat D/Instagram API: Response is Response{protocol=h2, code=200, message=, url=https://api.instagram.com/v1/users/self/media/recent/?access_token=1384558792.9ee905b.91162e4a2bee48d48ee9d677db864c6a}
10-15 16:34:17.476 29511-29720/com.spacebunny.hshen.inscat D/Instagram API: Response string is {"pagination": {}, "data": [{"id": "853859435326162587_1384558792", "user": {"id": "1384558792", "full_name": "Gregory", "profile_picture": "https://scontent.cdninstagram.com/t51.2885-19/10013205_337207629790338_1153867043_a.jpg", "username": "greggersaurus"}, "images": {"thumbnail": {"width": 150, "height": 150, "url": "https://scontent.cdninstagram.com/t51.2885-15/s150x150/e15/10809624_674872675960747_1192704288_n.jpg"}, "low_resolution": {"width": 320, "height": 320, "url": "https://scontent.cdninstagram.com/t51.2885-15/s320x320/e15/10809624_674872675960747_1192704288_n.jpg"}, "standard_resolution": {"width": 640, "height": 640, "url": "https://scontent.cdninstagram.com/t51.2885-15/e15/10809624_674872675960747_1192704288_n.jpg"}}, "created_time": "1416007998", "caption": {"id": "17852589613046793", "text": "Board games store/bar/cafe!", "created_time": "1416007998", "from": {"id": "1384558792", "full_name": "Gregory", "profile_picture": "https://scontent.cdninstagram.com/t51.2885-19/10013205_337207629790338_1153867043_a.jpg", "username": "greggersaurus"}}, "user_has_liked": false, "likes": {"count": 7}, "tags": [], "filter": "Normal", "comments": {"count": 2}, "type": "image", "link": "https://www.instagram.com/p/vZhKHqu0ab/", "location": null, "attribution": null, "users_in_photo": []}, {"id": "846620431073625340_1384558792", "user": {"id": "1384558792", "full_name": "Gregory", "profile_picture": "https://scontent.cdninstagram.com/t51.2885-19/10013205_337207629790338_1153867043_a.jpg", "username": "greggersaurus"}, "images": {"thumbnail": {"width": 150, "height": 150, "url": "https://scontent.cdninstagram.com/t51.2885-15/s150x150/e15/10735347_1519060361674371_814849855_n.jpg"}, "low_resolution": {"width": 320, "height": 320, "url": "https://scontent.cdninstagram.com/t51.2885-15/s320x320/e15/10735347_1519060361674371_814849855_n.jpg"}, "standard_resolution": {"width": 640, "height": 640, "url": "https://scontent.cdninstagram.com/t51.2885-15/e15/10735347_1519060361674371_814849855_n.jpg"}}, "created_time": "1415145041", "caption": {"id": "17852586094046793", "text": "Nexus9 family", "created_time": "1415145041", "from": {"id": "1384558792", "full_name": "Gregory", "profile_picture": "https://scontent.cdninstagram.com/t51.2885-19/10013205_337207629790338_1153867043_a.jpg", "username": "greggersaurus"}}, "user_has_liked": false, "likes": {"count": 1}, "tags": [], "filter": "Unknown", "comments": {"count": 0}, "type": "image", "link": "https://www.instagram.com/p/u_zMvlu0T8/", "location": null, "attribution": null, "users_in_photo": []}, {"id": "813860378851886304_1384558792", "user": {"id": "1384558792", "full_name": "Gregory", "profile_picture": "https://scontent.cdninstagram.com/t51.2885-19/10013205_337207629790338_1153867043_a.jpg", "username": "greggersaurus"}, "images": {"thumbnail": {"width": 150, "height": 150, "url": "https://scontent.cdninstagram.com/t51.2885-15/s150x150/e15/10684146_1486212014963063_1689147355_n.jpg"}, "low_resolution": {"width": 320, "height": 320, "url": "https://scontent.cdninstagram.com/t51.2885-15/s320x320/e15/10684146_1486212014963063_1689147355_n.jpg"}, "standard_resolution": {"width": 640, "height": 640, "url": "https://scontent.cdninstagram.com/t51.2885-15/e15/10684146_1486212014963063_1689147355_n.jpg"}}, "created_time": "1411239739", "caption": {"id": "17852568031046793", "text": "Waiting til we fall to our deaths!", "created_time": "1411239739", "from": {"id": "1384558792", "full_name": "Gregory", "profile_picture": "https://scontent.cdninstagram.com/t51.2885-19/10013205_337207629790338_1153867043_a.jpg", "username": "greggersaurus"}}, "user_has_liked": false, "likes": {"count": 4}, "tags": [], "filter": "Amaro", "comments": {"count": 2}, "type": "image", "link": "https://www.instagram.com/p/tLabPaO0Tg/", "location": null, "attribution": null, "users_in_photo": []}, {"id": "811756249476187671_1384558792", "user": {"id": "1384558792", "full_name": "Gregory", "profile_picture": "https://scontent.cdninstagram.com/t51.2885-19/100132
10-15 16:34:17.486 29511-29720/com.spacebunny.hshen.inscat D/Instagram API: User Media API response is {"code":200}
10-15 16:34:17.490 29511-29720/com.spacebunny.hshen.inscat D/Instagram API: Media info is [{"id":"853859435326162587_1384558792","user":{"id":"1384558792","full_name":"Gregory","profile_picture":"https://scontent.cdninstagram.com/t51.2885-19/10013205_337207629790338_1153867043_a.jpg","username":"greggersaurus"},"images":{"thumbnail":{"width":150,"height":150,"url":"https://scontent.cdninstagram.com/t51.2885-15/s150x150/e15/10809624_674872675960747_1192704288_n.jpg"},"low_resolution":{"width":320,"height":320,"url":"https://scontent.cdninstagram.com/t51.2885-15/s320x320/e15/10809624_674872675960747_1192704288_n.jpg"},"standard_resolution":{"width":640,"height":640,"url":"https://scontent.cdninstagram.com/t51.2885-15/e15/10809624_674872675960747_1192704288_n.jpg"}},"created_time":"1416007998","caption":{"id":"17852589613046793","text":"Board games store/bar/cafe!","created_time":"1416007998","from":{"id":"1384558792","full_name":"Gregory","profile_picture":"https://scontent.cdninstagram.com/t51.2885-19/10013205_337207629790338_1153867043_a.jpg","username":"greggersaurus"}},"user_has_liked":false,"likes":{"count":7},"tags":[],"filter":"Normal","comments":{"count":2},"type":"image","link":"https://www.instagram.com/p/vZhKHqu0ab/","location":null,"attribution":null,"users_in_photo":[]},{"id":"846620431073625340_1384558792","user":{"id":"1384558792","full_name":"Gregory","profile_picture":"https://scontent.cdninstagram.com/t51.2885-19/10013205_337207629790338_1153867043_a.jpg","username":"greggersaurus"},"images":{"thumbnail":{"width":150,"height":150,"url":"https://scontent.cdninstagram.com/t51.2885-15/s150x150/e15/10735347_1519060361674371_814849855_n.jpg"},"low_resolution":{"width":320,"height":320,"url":"https://scontent.cdninstagram.com/t51.2885-15/s320x320/e15/10735347_1519060361674371_814849855_n.jpg"},"standard_resolution":{"width":640,"height":640,"url":"https://scontent.cdninstagram.com/t51.2885-15/e15/10735347_1519060361674371_814849855_n.jpg"}},"created_time":"1415145041","caption":{"id":"17852586094046793","text":"Nexus9 family","created_time":"1415145041","from":{"id":"1384558792","full_name":"Gregory","profile_picture":"https://scontent.cdninstagram.com/t51.2885-19/10013205_337207629790338_1153867043_a.jpg","username":"greggersaurus"}},"user_has_liked":false,"likes":{"count":1},"tags":[],"filter":"Unknown","comments":{"count":0},"type":"image","link":"https://www.instagram.com/p/u_zMvlu0T8/","location":null,"attribution":null,"users_in_photo":[]},{"id":"813860378851886304_1384558792","user":{"id":"1384558792","full_name":"Gregory","profile_picture":"https://scontent.cdninstagram.com/t51.2885-19/10013205_337207629790338_1153867043_a.jpg","username":"greggersaurus"},"images":{"thumbnail":{"width":150,"height":150,"url":"https://scontent.cdninstagram.com/t51.2885-15/s150x150/e15/10684146_1486212014963063_1689147355_n.jpg"},"low_resolution":{"width":320,"height":320,"url":"https://scontent.cdninstagram.com/t51.2885-15/s320x320/e15/10684146_1486212014963063_1689147355_n.jpg"},"standard_resolution":{"width":640,"height":640,"url":"https://scontent.cdninstagram.com/t51.2885-15/e15/10684146_1486212014963063_1689147355_n.jpg"}},"created_time":"1411239739","caption":{"id":"17852568031046793","text":"Waiting til we fall to our deaths!","created_time":"1411239739","from":{"id":"1384558792","full_name":"Gregory","profile_picture":"https://scontent.cdninstagram.com/t51.2885-19/10013205_337207629790338_1153867043_a.jpg","username":"greggersaurus"}},"user_has_liked":false,"likes":{"count":4},"tags":[],"filter":"Amaro","comments":{"count":2},"type":"image","link":"https://www.instagram.com/p/tLabPaO0Tg/","location":null,"attribution":null,"users_in_photo":[]},{"id":"811756249476187671_1384558792","user":{"id":"1384558792","full_name":"Gregory","profile_picture":"https://scontent.cdninstagram.com/t51.2885-19/10013205_337207629790338_1153867043_a.jpg","username":"greggersaurus"},"images":{"thumbnail":{"width":150,"height":150,"url":"https://scontent.cdninstagram.com/t51.2885-15/s150x150/e15/10693495_306188679565395_1069015534_n.jpg"},"low_resolution":{"width":320,"heigh
10-15 16:34:17.495 29511-29720/com.spacebunny.hshen.inscat W/System.err: com.google.gson.JsonSyntaxException: java.lang.IllegalStateException: Expected a string but was BEGIN_OBJECT at line 1 column 724 path $[0].caption
10-15 16:34:17.496 29511-29720/com.spacebunny.hshen.inscat W/System.err:     at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$Adapter.read(ReflectiveTypeAdapterFactory.java:224)
10-15 16:34:17.496 29511-29720/com.spacebunny.hshen.inscat W/System.err:     at com.google.gson.internal.bind.TypeAdapterRuntimeTypeWrapper.read(TypeAdapterRuntimeTypeWrapper.java:41)
10-15 16:34:17.496 29511-29720/com.spacebunny.hshen.inscat W/System.err:     at com.google.gson.internal.bind.CollectionTypeAdapterFactory$Adapter.read(CollectionTypeAdapterFactory.java:82)
10-15 16:34:17.496 29511-29720/com.spacebunny.hshen.inscat W/System.err:     at com.google.gson.internal.bind.CollectionTypeAdapterFactory$Adapter.read(CollectionTypeAdapterFactory.java:61)
10-15 16:34:17.496 29511-29720/com.spacebunny.hshen.inscat W/System.err:     at com.google.gson.Gson.fromJson(Gson.java:887)
10-15 16:34:17.496 29511-29720/com.spacebunny.hshen.inscat W/System.err:     at com.google.gson.Gson.fromJson(Gson.java:852)
10-15 16:34:17.496 29511-29720/com.spacebunny.hshen.inscat W/System.err:     at com.google.gson.Gson.fromJson(Gson.java:801)
10-15 16:34:17.496 29511-29720/com.spacebunny.hshen.inscat W/System.err:     at com.spacebunny.hshen.inscat.utils.ModelUtils.toObject(ModelUtils.java:32)
10-15 16:34:17.496 29511-29720/com.spacebunny.hshen.inscat W/System.err:     at com.spacebunny.hshen.inscat.ins.Ins.parsePostResponse(Ins.java:123)
10-15 16:34:17.496 29511-29720/com.spacebunny.hshen.inscat W/System.err:     at com.spacebunny.hshen.inscat.ins.Ins.getPostListSelf(Ins.java:200)
10-15 16:34:17.496 29511-29720/com.spacebunny.hshen.inscat W/System.err:     at com.spacebunny.hshen.inscat.view.post_list.PostListFragment$LoadPostTask.doInBackground(PostListFragment.java:73)
10-15 16:34:17.496 29511-29720/com.spacebunny.hshen.inscat W/System.err:     at com.spacebunny.hshen.inscat.view.post_list.PostListFragment$LoadPostTask.doInBackground(PostListFragment.java:60)
10-15 16:34:17.496 29511-29720/com.spacebunny.hshen.inscat W/System.err:     at android.os.AsyncTask$2.call(AsyncTask.java:295)
10-15 16:34:17.496 29511-29720/com.spacebunny.hshen.inscat W/System.err:     at java.util.concurrent.FutureTask.run(FutureTask.java:237)
10-15 16:34:17.496 29511-29720/com.spacebunny.hshen.inscat W/System.err:     at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113)
10-15 16:34:17.496 29511-29720/com.spacebunny.hshen.inscat W/System.err:     at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588)
10-15 16:34:17.496 29511-29720/com.spacebunny.hshen.inscat W/System.err:     at java.lang.Thread.run(Thread.java:818)
10-15 16:34:17.496 29511-29720/com.spacebunny.hshen.inscat W/System.err: Caused by: java.lang.IllegalStateException: Expected a string but was BEGIN_OBJECT at line 1 column 724 path $[0].caption
10-15 16:34:17.497 29511-29720/com.spacebunny.hshen.inscat W/System.err:     at com.google.gson.stream.JsonReader.nextString(JsonReader.java:825)
10-15 16:34:17.497 29511-29720/com.spacebunny.hshen.inscat W/System.err:     at com.google.gson.internal.bind.TypeAdapters$16.read(TypeAdapters.java:418)
10-15 16:34:17.497 29511-29720/com.spacebunny.hshen.inscat W/System.err:     at com.google.gson.internal.bind.TypeAdapters$16.read(TypeAdapters.java:406)
10-15 16:34:17.497 29511-29720/com.spacebunny.hshen.inscat W/System.err:     at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$1.read(ReflectiveTypeAdapterFactory.java:129)
10-15 16:34:17.497 29511-29720/com.spacebunny.hshen.inscat W/System.err:     at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$Adapter.read(ReflectiveTypeAdapterFactory.java:220)
10-15 16:34:17.497 29511-29720/com.spacebunny.hshen.inscat W/System.err: 	... 16 more
10-15 16:36:33.563 29511-29511/com.spacebunny.hshen.inscat I/Timeline: Timeline: Activity_idle id: android.os.BinderProxy@6f1de3b time:351631002
10-15 16:36:35.289 29511-29511/com.spacebunny.hshen.inscat V/ViewRootImpl: Contents drawing finished : com.spacebunny.hshen.inscat/com.spacebunny.hshen.inscat.view.MainActivity
10-15 16:36:36.808 29511-29511/com.spacebunny.hshen.inscat I/ViewRootImpl: ViewRoot's KeyEvent { action=ACTION_DOWN, keyCode=KEYCODE_BACK, scanCode=0, metaState=0, flags=0x48, repeatCount=0, eventTime=351634215, downTime=351634215, deviceId=-1, source=0x101 } to com.android.internal.policy.PhoneWindow$DecorView{f7a73c4 V.E...... R......D 0,0-1440,2560}
10-15 16:36:36.823 29511-29511/com.spacebunny.hshen.inscat I/AudioManagerEx: AudioManagerEx created
10-15 16:36:36.845 29511-29511/com.spacebunny.hshen.inscat I/ViewRootImpl: ViewRoot's KeyEvent { action=ACTION_UP, keyCode=KEYCODE_BACK, scanCode=0, metaState=0, flags=0x48, repeatCount=0, eventTime=351634281, downTime=351634215, deviceId=-1, source=0x101 } to com.android.internal.policy.PhoneWindow$DecorView{f7a73c4 V.E...... R......D 0,0-1440,2560}
10-15 16:36:36.893 29511-29511/com.spacebunny.hshen.inscat W/SplitWindow: update focus... 
10-15 16:36:42.519 29511-29550/com.spacebunny.hshen.inscat W/cr_BindingManager: Cannot setInForeground() - never saw a connection for the pid: 29511

**Comment by gregoryenriquez** [comment]
fixed
