### ISSUE TITLE
"APINotAllowedError","error_message":"you cannot view this resource"

### ISSUE THREAD

**Issue by gregoryenriquez** [huishen12/Inscat#2]
10-15 21:03:15.794 21506-21525/? D/Instagram API: X-RateLimit-Remaining: 468
10-15 21:03:15.794 21506-21525/? D/Instagram API: Response is Response{protocol=h2, code=200, message=, url=https://api.instagram.com/v1/users/self/follows?access_token=1384558792.9ee905b.91162e4a2bee48d48ee9d677db864c6a}
10-15 21:03:15.797 21506-21525/? D/Instagram API: Response string is {"pagination": {}, "data": [{"id": "3258788853", "username": "annana121212", "full_name": "Anna", "profile_picture": "https://scontent.cdninstagram.com/t51.2885-19/s150x150/14063688_576469412541089_898075785_a.jpg"}], "meta": {"code": 200}}
10-15 21:03:15.802 21506-21525/? D/Instagram API: User Media API response is {"code":200}
10-15 21:03:15.802 21506-21525/? D/Instagram API: Media info is [{"id":"3258788853","username":"annana121212","full_name":"Anna","profile_picture":"https://scontent.cdninstagram.com/t51.2885-19/s150x150/14063688_576469412541089_898075785_a.jpg"}]
10-15 21:03:15.802 21506-21525/? D/ModelUtils: [{"id":"3258788853","username":"annana121212","full_name":"Anna","profile_picture":"https://scontent.cdninstagram.com/t51.2885-19/s150x150/14063688_576469412541089_898075785_a.jpg"}]
10-15 21:03:15.851 21506-21525/? D/Instagram API: X-RateLimit-Remaining: 467
10-15 21:03:15.851 21506-21525/? D/Instagram API: Response is Response{protocol=h2, code=400, message=, url=https://api.instagram.com/v1/users/3258788853/media/recent/?access_token=1384558792.9ee905b.91162e4a2bee48d48ee9d677db864c6a}
10-15 21:03:15.854 21506-21525/? D/Instagram API: Response string is {"meta": {"code": 400, "error_type": "APINotAllowedError", "error_message": "you cannot view this resource"}}
10-15 21:03:15.854 21506-21525/? D/Instagram API: User Media API response is {"code":400,"error_type":"APINotAllowedError","error_message":"you cannot view this resource"}
10-15 21:03:15.856 21506-21525/? E/AndroidRuntime: FATAL EXCEPTION: AsyncTask #1
                                                   Process: com.spacebunny.hshen.inscat, PID: 21506
                                                   java.lang.RuntimeException: An error occurred while executing doInBackground()
                                                       at android.os.AsyncTask$3.done(AsyncTask.java:309)
                                                       at java.util.concurrent.FutureTask.finishCompletion(FutureTask.java:354)
                                                       at java.util.concurrent.FutureTask.setException(FutureTask.java:223)
                                                       at java.util.concurrent.FutureTask.run(FutureTask.java:242)
                                                       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113)
                                                       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588)
                                                       at java.lang.Thread.run(Thread.java:818)
                                                    Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.String com.google.gson.JsonArray.toString()' on a null object reference
                                                       at com.spacebunny.hshen.inscat.ins.Ins.parsePostResponse(Ins.java:122)
                                                       at com.spacebunny.hshen.inscat.ins.Ins.getPostListUser(Ins.java:205)
                                                       at com.spacebunny.hshen.inscat.ins.Ins.getFollowedPostListSelf(Ins.java:220)
                                                       at com.spacebunny.hshen.inscat.view.post_list.PostListFragment$LoadPostTask.doInBackground(PostListFragment.java:72)
                                                       at com.spacebunny.hshen.inscat.view.post_list.PostListFragment$LoadPostTask.doInBackground(PostListFragment.java:60)
                                                       at android.os.AsyncTask$2.call(AsyncTask.java:295)
                                                       at java.util.concurrent.FutureTask.run(FutureTask.java:237)
                                                       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113) 
                                                       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588) 
                                                       at java.lang.Thread.run(Thread.java:818)

**Comment by gregoryenriquez** [comment]
something wrong with trying to view posts from admin of sandbox account
