### ISSUE TITLE
category crash

### ISSUE THREAD

**Issue by gregoryenriquez** [huishen12/Inscat#4]

**Comment by gregoryenriquez** [comment]
10-15 21:26:32.414 3666-3946/com.spacebunny.hshen.inscat E/AndroidRuntime: FATAL EXCEPTION: AsyncTask #4
                                                                           Process: com.spacebunny.hshen.inscat, PID: 3666
                                                                           java.lang.RuntimeException: An error occurred while executing doInBackground()
                                                                               at android.os.AsyncTask$3.done(AsyncTask.java:309)
                                                                               at java.util.concurrent.FutureTask.finishCompletion(FutureTask.java:354)
                                                                               at java.util.concurrent.FutureTask.setException(FutureTask.java:223)
                                                                               at java.util.concurrent.FutureTask.run(FutureTask.java:242)
                                                                               at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113)
                                                                               at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588)
                                                                               at java.lang.Thread.run(Thread.java:818)
                                                                            Caused by: java.lang.IllegalArgumentException: the bind value at index 1 is null
                                                                               at android.database.sqlite.SQLiteProgram.bindString(SQLiteProgram.java:164)
                                                                               at android.database.sqlite.SQLiteProgram.bindAllArgsAsStrings(SQLiteProgram.java:200)
                                                                               at android.database.sqlite.SQLiteDirectCursorDriver.query(SQLiteDirectCursorDriver.java:47)
                                                                               at android.database.sqlite.SQLiteDatabase.rawQueryWithFactory(SQLiteDatabase.java:1426)
                                                                               at android.database.sqlite.SQLiteDatabase.rawQuery(SQLiteDatabase.java:1365)
                                                                               at com.spacebunny.hshen.inscat.database.DBReaderHelper.getCategoryOfId(DBReaderHelper.java:172)
                                                                               at com.spacebunny.hshen.inscat.database.DBReaderHelper.getCategoryPostCount(DBReaderHelper.java:178)
                                                                               at com.spacebunny.hshen.inscat.view.post_detail.PostFragment$UpdateCategoryTask.doInBackground(PostFragment.java:139)
                                                                               at com.spacebunny.hshen.inscat.view.post_detail.PostFragment$UpdateCategoryTask.doInBackground(PostFragment.java:124)
                                                                               at android.os.AsyncTask$2.call(AsyncTask.java:295)
                                                                               at java.util.concurrent.FutureTask.run(FutureTask.java:237)
                                                                               at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113) 
                                                                               at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588) 
                                                                               at java.lang.Thread.run(Thread.java:818)
